"""Add tournament_id to Game model

Revision ID: 4c120bcef3c4
Revises: f79e4d7fc2e5
Create Date: 2025-06-09 15:31:15.435212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c120bcef3c4'
down_revision = 'f79e4d7fc2e5'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add the column as nullable first
    op.add_column('games', sa.Column('tournament_id', sa.Integer(), nullable=True))

    # Step 2: Populate existing rows with tournament_id = 1
    op.execute("UPDATE games SET tournament_id = 1")

    # Step 3: Alter the column to be NOT NULL
    op.alter_column('games', 'tournament_id', nullable=False)

    # Step 4: Add the foreign key constraint
    op.create_foreign_key(
        'fk_games_tournament',
        'games', 'tournaments',
        ['tournament_id'], ['id']
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tournament_id')

    # ### end Alembic commands ###
