"""Make display_name unique

Revision ID: 4e7d9dc1e2dd
Revises: 6e4c881ca35b
Create Date: 2025-06-07 09:59:50.623172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7d9dc1e2dd'
down_revision = '6e4c881ca35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_display_name', ['display_name'])
        batch_op.create_unique_constraint(None, ['display_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_users_display_name', type_='unique')

    # ### end Alembic commands ###
