"""Add scoring columns to users table

Revision ID: d97f29c87dd2
Revises: 0ffdc2c6b8a3
Create Date: 2025-06-05 21:27:52.609092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97f29c87dd2'
down_revision = '0ffdc2c6b8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfect_picks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('picks_scoring_one', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('picks_scoring_two', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invalid_picks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('invalid_picks')
        batch_op.drop_column('picks_scoring_two')
        batch_op.drop_column('picks_scoring_one')
        batch_op.drop_column('perfect_picks')

    # ### end Alembic commands ###
