"""Remove implicit unique constraint from display_name

Revision ID: f4decba491d7
Revises: 4c120bcef3c4
Create Date: 2025-06-10 22:14:31.989280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4decba491d7'
down_revision = '4c120bcef3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_display_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_display_name_key'), ['display_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
